---
title: 'Práctica 2: Limpieza y validación de los datos'
author: "Autores: Mikel Laburu Haro, Unai Mateos Corral"
date: "Curso 2018/2019"
output:
  pdf_document:
    highlight: zenburn
    toc: yes
  word_document: default
  html_document:
    highlight: default
    number_sections: yes
    theme: cosmo
    toc: yes
    toc_depth: 3
    includes:
      in_header: Cabecera.html
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(eval=T, echo=T)
```

******
# Introducción
******

## Carga de Datos

Se realiza la carga del conjunto de datos, as?? como la selección de las variables con las que se va a trabajar. Explicar por qué estas, y hacer una descripcion del dataset

```{r message= FALSE, warning=FALSE}
#Cargamos el Dataset
myData <- read.csv("BlackFriday.csv", header = TRUE, sep = ",")
# Mostrar las primeras 10 lineas del dataset y el contenido de 9 variables
head(myData[,1:9],10)
# Tipo de los datos de cada variable
sapply(myData,class)
```


```{r message= FALSE, warning=FALSE}
myDataAux <- myData[,c("Gender","Age","Occupation","City_Category","Stay_In_Current_City_Years","Marital_Status","Product_Category_1","Product_Category_2","Product_Category_3","Purchase")]
```


```{r message= FALSE, warning=FALSE}
colSums(is.na(myDataAux))
colSums(myDataAux == "?")
colSums(myDataAux == "")
myDataAux$Product_Category_2[is.na(myDataAux$Product_Category_2)] <- 0
myDataAux$Product_Category_3[is.na(myDataAux$Product_Category_3)] <- 0
str(myDataAux)
myDataAux$Product_Category_2 <- as.integer(myDataAux$Product_Category_2)
myDataAux$Product_Category_3 <- as.integer(myDataAux$Product_Category_3)
str(myDataAux)
```



```{r message= FALSE, warning=FALSE}
#Comentario
boxplot(myDataAux$Purchase)
valoresAtiPurch <- boxplot.stats(myDataAux$Purchase)$out
length(valoresAtiPurch)
valoresAtiPurch[0:69]
```

```{r message= FALSE, warning=FALSE}
#Comentario
```
